### ISSUE TITLE
Typos from The Origins I: HTML

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/html-101#11]
Hello team,

Please find below a list of typos from The Origins I: HTML lessons.

### 04. Corporate Talk
- Replace 'mission-critial' with 'mission-critical', see typo1.png. 👇
![typo1](https://github.com/codedex-io/html-101/assets/48260426/eb9de3b3-e576-4238-8242-70ab2bf0b9df)

### 11. Wiki Article
- Replace 'of' with 'about', see typo2.png. 👇
![typo2](https://github.com/codedex-io/html-101/assets/48260426/0ed562aa-33ba-490e-b994-8b02c247634b)

### 13. Power Rangers
- Replace 'have' with 'has', see typo3.png. 👇
![typo3](https://github.com/codedex-io/html-101/assets/48260426/7ce767f0-fc5a-4d2d-a35d-6f452ec15985)

### 14. MySpace Top 8
- Add 'with' after 'you', see typo4.png. 👇
![typo4](https://github.com/codedex-io/html-101/assets/48260426/a7ee92f2-df4f-45c7-a1ad-85eb752533ee)

**Comment by sonnynomnom** [comment]
ALL FIXED!!! Great one Milan.
