### ISSUE TITLE
fix: typos in 10_craigslist_ad.html

### ISSUE THREAD

**Issue by beingsie** [codedex-io/html-101#12]
#### Description:
- In the provided HTML code, there is a comment character `-->` within the `<h1>` tag. This character appears to be a typo and should be removed.

#### Expected Behavior
- The `<h1>` heading should only contain the text "Didgeridoo. Needs work."

#### Description:
- There is a typo in the list item within the `<ul>` element.
  - The list item reads, "do NOT contact me with unsolicited services or offerse," where "offerse" appears to be a typo and should be corrected to "offers."

**Comment by beingsie** [comment]
I have also added an extra commit for cleaner code that removes an extra space within the `h1`.

**Screenshot of original code:**
<img width="375" alt="image" src="https://github.com/codedex-io/html-101/assets/140430987/1b1188e9-9d30-495a-af7a-4711ea33a6bf">

**Comment by sonnynomnom** [comment]
Very nice! Closed~~~
