### ISSUE TITLE
Class "top-8-row" not used in file 14_top_8.html

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/html-101#29]
Hello team,

There is a class in this [file](https://github.com/codedex-io/html-101/blob/main/2-structure/14_top_8.html) that is never used in the `<style>` tag. Please see the attached picture for more context. 👇
![Screenshot_2023-10-29_23-23-19](https://github.com/codedex-io/html-101/assets/48260426/cf7f6dde-d901-40f7-9f8f-f5cf7f1a6d66)

From a beginner perspective, having a class that is not used in the `<style>` tag is unnecessary and can cause confusion in understanding the context of the solution.

### Proposed solutions

1. Remove unused tags.
2. Add some CSS parameters to the class "top-8-row".
3. Rename the second class "top-8-row" to "bottom-8-row" and leave them unused, that makes it easier to understand which row has what.

**Comment by Dusch4593** [comment]
I'm closing this issue for now; see [this comment](https://github.com/codedex-io/html-101/pull/28#issuecomment-1786252775) in the connected PR.
