### ISSUE TITLE
[Bug]: a deprecated HTML tag found in 07_band.html

### ISSUE THREAD

**Issue by CBID2** [codedex-io/html-101#45]
## Problem
In the `07_band.html` file, I noticed that the `<marquee>` tag is used(see below code snippet). According to [Deque University](https://dequeuniversity.com/rules/axe/4.1/marquee), this HTML tag is no longer in use as it only works with most browsers, which would make it difficult for learners to view it in the lesson. 

```html
 Here is a <a href="https://www.blackpinkmusic.com/">link</a> to BLACKPINK's website!
  <h4>Their <u>top 5</u> songs are:</h4>
  <ol>
    <li>마지막처럼 (As If It's Your Last) - 2017</li>
    <li>뚜두뚜두 (DDU-DU DDU-DU) - 2018</li>
    <li>How You Like That - 2020</li>
    <li>Kill This Love - 2019 </li>
    <li>붐바야 (BOOMBAYAH) - 2016</li>
  </ol>
  <marquee>Hwaiting! 🫰</marquee>
  ```
  ## Solution
 Since `<marquee>` tag was often used to insert a scrolling area of text, the `<canvas>` tag would be a good replacement as it has a similar effect and it is [compatible with all sorts of browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas).

**Comment by sonnynomnom** [comment]
closing: https://www.codedex.io/community/monthly-challenge/submission/T3tNDfa5zFh7Vj0xxInX
